version: "3.9"
services:
  app:
    build: .
    command: ["npx", "ts-node", "./index.ts"]
    restart: unless-stopped
    depends_on:
      - mysql_db
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: students_db 
    networks:
      - cloudappnetwork
  mysql_db:
    platform: linux
    image: mysql
    container_name: mysql_db
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: students_db
    networks:
    - cloudappnetwork

    volumes:
      - "./sql/students_db.sql:/docker-entrypoint-initdb.d/init.sql"
      - mysqldata:/var/lib/mysql

networks:
  cloudappnetwork:

volumes:
  mysqldata: